name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.0', '7.1', '7.2.', '7.3', '7.4']
        dependencies: ['']
        include:
          - { php-version: '7.0', dependencies: '--prefer-lowest' }

    name: PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: 
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer update --no-interaction ${{ matrix.dependencies }}

      - name: Run tests
        run: |
          php vendor/bin/phpunit

      - name: Run mutation testing
        run: |
          php vendor/bin/infection --min-msi=80 --min-covered-msi=80 --log-verbosity=2 --threads=$(nproc)
          
