name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.3', '7.4']
        dependencies: ['']
        include:
          - { php-version: '7.3', dependencies: '--prefer-lowest' }
          - { php-version: '8.0', dependencies: '--ignore-platform-req=php' }

    continue-on-error: ${{ matrix.php-version == '8.0' }}
    name: PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: 
          coverage: pcov
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress ${{ matrix.dependencies }}

      - name: Run tests
        run: |
          php vendor/bin/phpunit
